{% set name = "ezyrb" %}
{% set version = "1.3.0.post2210" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezyrb-{{ version }}.tar.gz
  sha256: b096c7f952d7b2e575483bc075ef2e180355d367d8a85e49ef635f50d3340bb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future
    - matplotlib-base
    - numpy
    - python >=3.6
    - scikit-learn >=1.0
    - scipy
    - pytorch

test:
  imports:
    - ezyrb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mathLab/EZyRB
  summary: Easy Reduced Basis
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
