{% set name = "ezyrb" %}
{% set version = "1.3.0.post2312" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezyrb-{{ version }}.tar.gz
  sha256: f83cb0b8e1432b380a62e49c9ff75d3e1c00753cf69e4db5bf9f99b6d4bbe597

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - future
    - numpy
    - scipy
    - matplotlib-base
    - scikit-learn >=1.0
    - pytorch

test:
  imports:
    - ezyrb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mathLab/EZyRB
  summary: Easy Reduced Basis
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
