{% set name = "ezyrb" %}
{% set version = "1.3.0.post2403" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezyrb-{{ version }}.tar.gz
  sha256: 44d82d01d77e41d302e91b39e9135799a753feef72b038d53936b48a1e182aa8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - future
    - numpy
    - scipy
    - matplotlib-base
    - scikit-learn >=1.0
    - pytorch

test:
  imports:
    - ezyrb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mathLab/EZyRB
  summary: Easy Reduced Basis
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
