{% set name = "ezyrb" %}
{% set version = "1.3.0.post2401" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezyrb-{{ version }}.tar.gz
  sha256: bc2aae98865c20673587b70ccb71970547a4220650651837f736762ba55e6eae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - future
    - numpy
    - scipy
    - matplotlib-base
    - scikit-learn >=1.0
    - pytorch

test:
  imports:
    - ezyrb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mathLab/EZyRB
  summary: Easy Reduced Basis
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
